spring.application.name=finance-tracker

# Datasource
# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker
spring.datasource.username=finance_user
spring.datasource.password=finance_password

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
